"""Save architect pipeline results to disk (user-friendly folders)."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

from architect_pipeline import ArchitectResult
from paths import PACKAGE_DIR

# Repo root: arbitrage-by-JAC/
REPO_ROOT = PACKAGE_DIR.parent
DEFAULT_OUTPUT_ROOT = REPO_ROOT / "harvester" / "generated"


def _safe_name(text: str) -> str:
    return re.sub(r"[^\w\-]+", "_", text).strip("_")[:60] or "phase"


def save_architect_result(
    result: ArchitectResult,
    *,
    output_root: Path | None = None,
) -> Path:
    """
    Write plan + each phase to:
      harvester/generated/YYYY-MM-DD_HHMMSS/
        plan.json
        README.txt
        phase_01_<title>.md
    """
    root = output_root or DEFAULT_OUTPUT_ROOT
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H%M%S")
    out_dir = root / stamp
    out_dir.mkdir(parents=True, exist_ok=True)

    plan_path = out_dir / "plan.json"
    plan_path.write_text(json.dumps(result.plan_json, indent=2), encoding="utf-8")

    readme = [
        "Generated by local-llm Architect mode.",
        f"Folder: {out_dir}",
        "",
        "Files:",
        f"  - {plan_path.name}",
    ]
    for p in result.phases:
        fname = f"phase_{p.step:02d}_{_safe_name(p.title)}.md"
        readme.append(f"  - {fname}")
    (out_dir / "README.txt").write_text("\n".join(readme), encoding="utf-8")

    for p in result.phases:
        fname = f"phase_{p.step:02d}_{_safe_name(p.title)}.md"
        header = f"# Phase {p.step}: {p.title}\n\n"
        (out_dir / fname).write_text(header + p.content, encoding="utf-8")

    combined = out_dir / "ALL_PHASES.txt"
    parts = [f"=== PLAN ===\n{plan_path.read_text(encoding='utf-8')}\n"]
    for p in result.phases:
        parts.append(f"\n\n=== PHASE {p.step}: {p.title} ===\n{p.content}")
    combined.write_text("".join(parts), encoding="utf-8")

    return out_dir


def default_mega_prompt_path() -> Path:
    return PACKAGE_DIR / "prompts" / "mega_prompt.txt"


def load_mega_prompt_file() -> str:
    path = default_mega_prompt_path()
    if path.is_file():
        return path.read_text(encoding="utf-8")
    return (
        "# Edit this file with your big project prompt (lines starting with # are notes).\n"
        "# Save, then in the web app click 'Reload my prompt file' or run scripts\\run_architect_easy.bat\n\n"
        "Describe your arbitrage pipeline project here...\n"
    )


def save_mega_prompt_file(text: str) -> Path:
    path = default_mega_prompt_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path
