"""Canonical team tokens for fuzzy cross-source matching."""

from __future__ import annotations

# NBA examples; extend per league as needed
NBA_ALIASES: dict[str, str] = {
    "atl": "atlanta hawks",
    "hawks": "atlanta hawks",
    "atlanta": "atlanta hawks",
    "bos": "boston celtics",
    "celtics": "boston celtics",
    "bkn": "brooklyn nets",
    "nets": "brooklyn nets",
    "brooklyn": "brooklyn nets",
    "cha": "charlotte hornets",
    "hornets": "charlotte hornets",
    "charlotte": "charlotte hornets",
    "chi": "chicago bulls",
    "bulls": "chicago bulls",
    "chicago": "chicago bulls",
    "cle": "cleveland cavaliers",
    "cavaliers": "cleveland cavaliers",
    "cavs": "cleveland cavaliers",
    "dal": "dallas mavericks",
    "mavericks": "dallas mavericks",
    "mavs": "dallas mavericks",
    "den": "denver nuggets",
    "nuggets": "denver nuggets",
    "det": "detroit pistons",
    "pistons": "detroit pistons",
    "gsw": "golden state warriors",
    "warriors": "golden state warriors",
    "golden state": "golden state warriors",
    "hou": "houston rockets",
    "rockets": "houston rockets",
    "ind": "indiana pacers",
    "pacers": "indiana pacers",
    "lac": "los angeles clippers",
    "clippers": "los angeles clippers",
    "lal": "los angeles lakers",
    "lakers": "los angeles lakers",
    "mem": "memphis grizzlies",
    "grizzlies": "memphis grizzlies",
    "mia": "miami heat",
    "heat": "miami heat",
    "mil": "milwaukee bucks",
    "bucks": "milwaukee bucks",
    "min": "minnesota timberwolves",
    "timberwolves": "minnesota timberwolves",
    "wolves": "minnesota timberwolves",
    "nop": "new orleans pelicans",
    "pelicans": "new orleans pelicans",
    "nyk": "new york knicks",
    "knicks": "new york knicks",
    "okc": "oklahoma city thunder",
    "thunder": "oklahoma city thunder",
    "orl": "orlando magic",
    "magic": "orlando magic",
    "phi": "philadelphia 76ers",
    "sixers": "philadelphia 76ers",
    "76ers": "philadelphia 76ers",
    "phx": "phoenix suns",
    "suns": "phoenix suns",
    "por": "portland trail blazers",
    "blazers": "portland trail blazers",
    "trail blazers": "portland trail blazers",
    "sac": "sacramento kings",
    "kings": "sacramento kings",
    "sas": "san antonio spurs",
    "spurs": "san antonio spurs",
    "tor": "toronto raptors",
    "raptors": "toronto raptors",
    "uta": "utah jazz",
    "jazz": "utah jazz",
    "was": "washington wizards",
    "wizards": "washington wizards",
}

NFL_ALIASES: dict[str, str] = {
    "kc": "kansas city chiefs",
    "chiefs": "kansas city chiefs",
    "sf": "san francisco 49ers",
    "49ers": "san francisco 49ers",
    "dal": "dallas cowboys",
    "cowboys": "dallas cowboys",
    "phi": "philadelphia eagles",
    "eagles": "philadelphia eagles",
}

LEAGUE_ALIASES: dict[str, dict[str, str]] = {
    "basketball_nba": NBA_ALIASES,
    "americanfootball_nfl": NFL_ALIASES,
}
